export const adatLista = [
    'kepek/kep1.jpg',
    'kepek/kep10.jpg',
    'kepek/kep11.jpg',
    'kepek/kep12.jpg',
    'kepek/kep13.jpg',
    'kepek/kep14.jpg',
    'kepek/kep15.jpg',
    'kepek/kep16.jpg',
    'kepek/kep1.jpg',
    'kepek/kep10.jpg',
    'kepek/kep11.jpg',
    'kepek/kep12.jpg',
    'kepek/kep13.jpg',
    'kepek/kep14.jpg',
    'kepek/kep15.jpg',
    'kepek/kep16.jpg',
]